//! Companion automation configs: Unpackerr, Janitorr, and guided
//! setups for the ones Porthole can't fully wire (Cleanuparr,
//! Maintainerr, Tautulli, Jellystat, Wizarr, Kometa).
//!
//! Honest boundaries, like Bazarr in Phase 7:
//! - Automate what Porthole can verify (API keys it holds).
//! - Guide the rest with exact values (never fake automation).

/// Unpackerr env file: *arr URLs + API keys.
/// Porthole reads the keys from the *arr config.xml files.
pub fn unpackerr_env(sonarr_key: &str, radarr_key: &str, lidarr_key: Option<&str>) -> String {
    let mut out = format!(
        "# Generated by Porthole — Unpackerr *arr connections.\n\
         UN_SONARR_0_URL=http://sonarr:8989\n\
         UN_SONARR_0_API_KEY={sonarr_key}\n\
         UN_RADARR_0_URL=http://radarr:7878\n\
         UN_RADARR_0_API_KEY={radarr_key}\n"
    );
    if let Some(k) = lidarr_key {
        out.push_str(&format!(
            "UN_LIDARR_0_URL=http://lidarr:8686\nUN_LIDARR_0_API_KEY={k}\n"
        ));
    }
    out
}

/// Janitorr application.yml — ALWAYS starts with dry-run: true.
/// (Research trap #234: misconfigured expiration + bad watch data =
/// mass deletion. Dry-run first, always.)
pub fn janitorr_config() -> String {
    String::from(
        "# Generated by Porthole — Janitorr starts in DRY-RUN.\n\
         # It logs what WOULD be deleted. Review, then set dry-run: false.\n\
         dry-run: true\n\
         \n\
         # Check daily at 2 AM.\n\
         media-cleanup-schedule: \"0 0 2 * * ?\"\n\
         tag-cleanup-schedule: \"0 0 3 * * ?\"\n\
         \n\
         # Conservative: only clean what hasn't been watched in a year,\n\
         # and only when disk is over 90% full.\n\
         # (Tune in Janitorr's UI after you've reviewed a dry-run.)\n\
         leaving-soon: 400d\n\
         \n\
         # Never delete these, even if they match.\n\
         exclusion-tags:\n\
         \x20\x20 - janitorr_keep\n\
         \x20\x20 - janitor-keep\n\
         \n\
         # Whole-show handling OFF (treats a series as one unit — dangerous).\n\
         whole-tv-show: false\n",
    )
}

/// Guided steps for Cleanuparr (its config schema isn't stable enough
/// to pre-seed safely; Porthole shows the exact values).
pub fn cleanuparr_manual_steps(sonarr_key: &str, radarr_key: &str) -> Vec<String> {
    vec![
        "Open Cleanuparr at http://localhost:11011.".to_string(),
        format!("Add Sonarr: URL `http://sonarr:8989`, API key `{sonarr_key}`."),
        format!("Add Radarr: URL `http://radarr:7878`, API key `{radarr_key}`."),
        "Enable the cleaners you want (stalled, failed-import, slow).".to_string(),
        "It re-searches automatically when it removes something.".to_string(),
    ]
}

/// Guided steps for Tautulli (Plex token + enable the API).
pub fn tautulli_manual_steps(plex_token: &str) -> Vec<String> {
    vec![
        "Open Tautulli at http://localhost:8181.".to_string(),
        "Settings → Plex Media Server: add your server,".to_string(),
        format!("use this token (Porthole read it from Plex): `{plex_token}`"),
        "Settings → Web Interface → API: ENABLE it (it's off by default).".to_string(),
        "Copy the API key — Maintainerr needs it.".to_string(),
    ]
}

/// Guided steps for Maintainerr (conservative, review-first).
pub fn maintainerr_manual_steps() -> Vec<String> {
    vec![
        "Open Maintainerr at http://localhost:6246.".to_string(),
        "Add Plex/Jellyfin, Sonarr, Radarr, and Seerr (API keys from Porthole).".to_string(),
        "Add Tautulli (Plex) or Jellystat (Jellyfin) as the watch-stats source.".to_string(),
        "Start with the example rule DISABLED — review what it WOULD do first.".to_string(),
        "Maintainerr holds matches in a collection before acting. Nothing is instant.".to_string(),
    ]
}

/// Guided steps for Wizarr (invites for friends/family).
pub fn wizarr_manual_steps() -> Vec<String> {
    vec![
        "Open Wizarr at http://localhost:5690 and create your admin account.".to_string(),
        "Add your media server (Plex token or Jellyfin URL + API key).".to_string(),
        "Link Seerr so invitees can request media.".to_string(),
        "Create an invite link — expiry and permissions are per-invite.".to_string(),
    ]
}

/// Guided steps for Kometa (Plex only, needs a TMDb key).
pub fn kometa_manual_steps() -> Vec<String> {
    vec![
        "Kometa only works with Plex (there's no Jellyfin equivalent).".to_string(),
        "Get a free TMDb API key at themoviedb.org/settings/api.".to_string(),
        format!(
            "Edit {}/configs/kometa/config.yml: add your Plex token and TMDb key.",
            "<install>"
        ),
        "Kometa's default config is ~200 lines — Porthole ships a sane starter.".to_string(),
    ]
}

/// Kometa starter config (Plex token + TMDb key filled in by the user).
pub fn kometa_config() -> String {
    String::from(
        "# Generated by Porthole — Kometa starter (Plex only).\n\
         # Fill in your tokens, then: docker restart kometa\n\
         libraries:\n\
         \x20\x20 Movies:\n\
         \x20\x20\x20\x20 collection_files:\n\
         \x20\x20\x20\x20\x20\x20 - default: basic\n\
         \x20\x20\x20\x20\x20\x20 - default: imdb\n\
         \x20\x20 TV Shows:\n\
         \x20\x20\x20\x20 collection_files:\n\
         \x20\x20\x20\x20\x20\x20 - default: basic\n\
         \n\
         plex:\n\
         \x20\x20 url: http://plex:32400\n\
         \x20\x20 token: YOUR_PLEX_TOKEN_HERE\n\
         \n\
         tmdb:\n\
         \x20\x20 apikey: YOUR_TMDB_KEY_HERE\n\
         \n\
         settings:\n\
         \x20\x20 cache: true\n\
         \x20\x20 cache_expiration: 60\n\
         \x20\x20 collection_mode: default\n",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unpackerr_env_has_keys() {
        let env = unpackerr_env("skey", "rkey", Some("lkey"));
        assert!(env.contains("UN_SONARR_0_API_KEY=skey"));
        assert!(env.contains("UN_RADARR_0_API_KEY=rkey"));
        assert!(env.contains("UN_LIDARR_0_API_KEY=lkey"));
    }

    #[test]
    fn janitorr_starts_dry_run() {
        let cfg = janitorr_config();
        assert!(cfg.contains("dry-run: true"));
        assert!(cfg.contains("whole-tv-show: false"));
    }

    #[test]
    fn kometa_config_is_plex_only() {
        let cfg = kometa_config();
        assert!(cfg.contains("http://plex:32400"));
        assert!(cfg.contains("YOUR_TMDB_KEY_HERE"));
    }
}
