//! Expert *arr configuration via Configarr.
//!
//! Shiphand does not hand-configure Sonarr/Radarr — it generates a
//! Configarr `config.yml` from the user's answer(s) and runs Configarr
//! (a one-shot Docker job) to sync the TRaSH-Guides quality profiles,
//! custom formats, and naming into the *arrs. Idempotent: re-running
//! reverts any hand-edits, which is the point.
//!
//! Template IDs were verified against the recyclarr/config-templates
//! repo (templates.json) in October 2026. If Configarr can't resolve one,
//! it fails loudly and Shiphand shows the log — never silently.

/// Configarr container image.
pub const IMAGE: &str = "ghcr.io/raydak-labs/configarr:latest";

/// Docker network the fleet lives on (from the installer's compose).
pub const NETWORK: &str = "media-network";

/// Recyclarr template IDs, verified against templates.json (Oct 2026).
pub fn sonarr_template(four_k: bool) -> &'static str {
    if four_k {
        "web-2160p"
    } else {
        "web-1080p"
    }
}

pub fn radarr_template(four_k: bool) -> &'static str {
    if four_k {
        "uhd-bluray-web"
    } else {
        "hd-bluray-web"
    }
}

/// Render Configarr's `config.yml`.
///
/// - `four_k`: true → 4K profiles (Sonarr WEB-2160p, Radarr UHD Bluray +
///   WEB), false → 1080p (Sonarr WEB-1080p, Radarr HD Bluray + WEB).
/// - Naming is always the TRaSH `default` (covers standard, daily, and
///   anime formats) — verified against Configarr's docs.
///
/// Why only one question: the research proposed four (resolution, HDR,
/// HD-audio, anime), but verification showed the UHD profiles already
/// encode optimal HDR/audio custom-format scores, and anime naming is
/// always applied via `episodes.anime: default`. Asking the other three
/// would be theater, not configuration.
pub fn render_config_yml(four_k: bool) -> String {
    let sonarr_tpl = sonarr_template(four_k);
    let radarr_tpl = radarr_template(four_k);
    format!(
        "# Generated by Shiphand — do not hand-edit.\n\
         # Change your quality answer (Care → Apply expert quality profiles)\n\
         # and re-run; Configarr reverts hand-edits by design.\n\
         trashGuideUrl: https://github.com/TRaSH-Guides/Guides\n\
         recyclarrConfigUrl: https://github.com/recyclarr/config-templates\n\
         \n\
         sonarr:\n\
         \x20 instance1:\n\
         \x20\x20\x20 base_url: http://sonarr:8989\n\
         \x20\x20\x20 api_key: !secret SONARR_API_KEY\n\
         \x20\x20\x20 quality_definition:\n\
         \x20\x20\x20\x20\x20 type: series\n\
         \x20\x20\x20 include:\n\
         \x20\x20\x20\x20\x20 - template: {sonarr_tpl}\n\
         \x20\x20\x20 media_naming:\n\
         \x20\x20\x20\x20\x20 series: default\n\
         \x20\x20\x20\x20\x20 season: default\n\
         \x20\x20\x20\x20\x20 episodes:\n\
         \x20\x20\x20\x20\x20\x20\x20 rename: true\n\
         \x20\x20\x20\x20\x20\x20\x20 standard: default\n\
         \x20\x20\x20\x20\x20\x20\x20 daily: default\n\
         \x20\x20\x20\x20\x20\x20\x20 anime: default\n\
         \n\
         radarr:\n\
         \x20 instance1:\n\
         \x20\x20\x20 base_url: http://radarr:7878\n\
         \x20\x20\x20 api_key: !secret RADARR_API_KEY\n\
         \x20\x20\x20 quality_definition:\n\
         \x20\x20\x20\x20\x20 type: movie\n\
         \x20\x20\x20 include:\n\
         \x20\x20\x20\x20\x20 - template: {radarr_tpl}\n\
         \x20\x20\x20 media_naming:\n\
         \x20\x20\x20\x20\x20 folder: default\n\
         \x20\x20\x20\x20\x20 movie:\n\
         \x20\x20\x20\x20\x20\x20\x20 rename: true\n\
         \x20\x20\x20\x20\x20\x20\x20 standard: default\n"
    )
}

/// Render `secrets.yml` with the *arr API keys.
pub fn render_secrets_yml(sonarr_api_key: &str, radarr_api_key: &str) -> String {
    format!(
        "# Generated by Shiphand — secrets. Never commit this file.\n\
         SONARR_API_KEY: \"{sonarr}\"\n\
         RADARR_API_KEY: \"{radarr}\"\n",
        sonarr = sonarr_api_key.replace('"', "\\\""),
        radarr = radarr_api_key.replace('"', "\\\""),
    )
}

/// Read an *arr API key from its config.xml (`<ApiKey>…</ApiKey>`).
pub fn arr_api_key(install_dir: &std::path::Path, service: &str) -> Result<String, String> {
    let path = install_dir.join(format!("configs/{service}/config.xml"));
    let raw = std::fs::read_to_string(&path)
        .map_err(|_| format!("no config.xml for {service} — is it installed?"))?;
    let key = "<ApiKey>";
    let start = raw
        .find(key)
        .ok_or_else(|| format!("no API key in {service}/config.xml"))?
        + key.len();
    let end = raw[start..]
        .find("</ApiKey>")
        .ok_or_else(|| format!("could not parse API key from {service}/config.xml"))?;
    let api_key = raw[start..start + end].trim().to_string();
    if api_key.is_empty() {
        return Err(format!("empty API key in {service}/config.xml"));
    }
    Ok(api_key)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_selection() {
        assert_eq!(sonarr_template(false), "web-1080p");
        assert_eq!(sonarr_template(true), "web-2160p");
        assert_eq!(radarr_template(false), "hd-bluray-web");
        assert_eq!(radarr_template(true), "uhd-bluray-web");
    }

    #[test]
    fn config_yml_has_both_instances_and_naming() {
        let yml = render_config_yml(false);
        assert!(yml.contains("http://sonarr:8989"));
        assert!(yml.contains("http://radarr:7878"));
        assert!(yml.contains("!secret SONARR_API_KEY"));
        assert!(yml.contains("- template: web-1080p"));
        assert!(yml.contains("- template: hd-bluray-web"));
        assert!(yml.contains("rename: true"));
        assert!(yml.contains("anime: default"));
        assert!(yml.contains("trashGuideUrl: https://github.com/TRaSH-Guides/Guides"));

        let yml4k = render_config_yml(true);
        assert!(yml4k.contains("- template: web-2160p"));
        assert!(yml4k.contains("- template: uhd-bluray-web"));
    }

    #[test]
    fn secrets_yml_quotes_keys() {
        let yml = render_secrets_yml("abc123", "def456");
        assert!(yml.contains("SONARR_API_KEY: \"abc123\""));
        assert!(yml.contains("RADARR_API_KEY: \"def456\""));
    }

    #[test]
    fn reads_api_key_from_config_xml() {
        let dir = std::env::temp_dir().join("shiphand-configarr-test");
        let cfg = dir.join("configs/sonarr");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&cfg).unwrap();
        std::fs::write(
            cfg.join("config.xml"),
            "<Config><ApiKey>key123abc</ApiKey><Port>8989</Port></Config>",
        )
        .unwrap();
        assert_eq!(arr_api_key(&dir, "sonarr").unwrap(), "key123abc");
        assert!(arr_api_key(&dir, "radarr").is_err());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
