//! Optional fleet members: Lidarr (music), Bazarr (subtitles),
//! Sportarr (sports).
//!
//! Porthole doesn't patch the installer's `docker-compose.yml`. Instead it
//! generates `docker-compose.override.yml`, which the installer's compose
//! wrapper auto-discovers (it `cd`s into the install dir). Deleting the
//! override removes the extras; regenerating it changes the selection.
//! Idempotent and non-destructive to the base fleet.

use anyhow::{Context, Result};
use std::path::Path;

/// Which optional services the user wants.
#[derive(Clone, Copy, Debug, Default)]
pub struct Extras {
    pub lidarr: bool,
    pub bazarr: bool,
    pub sportarr: bool,
    pub autobrr: bool,
}

impl Extras {
    pub fn any(&self) -> bool {
        self.lidarr || self.bazarr || self.sportarr || self.autobrr
    }
}

/// Render `docker-compose.override.yml`.
///
/// Conventions mirror the installer's compose: localhost-bound ports,
/// `${CONFIG_DIR}/<svc>:/config`, `${DATA_DIR}:/data`, `media-network`,
/// PUID/PGID/TZ from the environment. Bazarr gets a 768 MB cap —
/// upstream can balloon without one.
pub fn render_override_yml(extras: &Extras) -> String {
    let mut out = String::from(
        "# Generated by Porthole — optional fleet members.\n\
         # Delete this file (or untick the extras in Care) to remove them.\n\
         # The installer's docker-compose.yml is never touched.\n\
         services:\n",
    );
    if extras.lidarr {
        out.push_str(
            "  lidarr:\n\
             \x20\x20\x20 image: lscr.io/linuxserver/lidarr:latest\n\
             \x20\x20\x20 container_name: lidarr\n\
             \x20\x20\x20 restart: unless-stopped\n\
             \x20\x20\x20 networks:\n\
             \x20\x20\x20\x20\x20 - media-network\n\
             \x20\x20\x20 ports:\n\
             \x20\x20\x20\x20\x20 - \"127.0.0.1:8686:8686\"\n\
             \x20\x20\x20 environment:\n\
             \x20\x20\x20\x20\x20 - PUID=${PUID:-1000}\n\
             \x20\x20\x20\x20\x20 - PGID=${PGID:-1000}\n\
             \x20\x20\x20\x20\x20 - TZ=${TZ:-UTC}\n\
             \x20\x20\x20 volumes:\n\
             \x20\x20\x20\x20\x20 - \"${CONFIG_DIR}/lidarr:/config\"\n\
             \x20\x20\x20\x20\x20 - \"${DATA_DIR}:/data\"\n",
        );
    }
    if extras.bazarr {
        out.push_str(
            "  bazarr:\n\
             \x20\x20\x20 image: lscr.io/linuxserver/bazarr:latest\n\
             \x20\x20\x20 container_name: bazarr\n\
             \x20\x20\x20 restart: unless-stopped\n\
             \x20\x20\x20 mem_limit: 768m\n\
             \x20\x20\x20 networks:\n\
             \x20\x20\x20\x20\x20 - media-network\n\
             \x20\x20\x20 ports:\n\
             \x20\x20\x20\x20\x20 - \"127.0.0.1:6767:6767\"\n\
             \x20\x20\x20 environment:\n\
             \x20\x20\x20\x20\x20 - PUID=${PUID:-1000}\n\
             \x20\x20\x20\x20\x20 - PGID=${PGID:-1000}\n\
             \x20\x20\x20\x20\x20 - TZ=${TZ:-UTC}\n\
             \x20\x20\x20 volumes:\n\
             \x20\x20\x20\x20\x20 - \"${CONFIG_DIR}/bazarr:/config\"\n\
             \x20\x20\x20\x20\x20 - \"${DATA_DIR}:/data\"\n",
        );
    }
    if extras.autobrr {
        out.push_str(
            "  autobrr:\n\
             \x20\x20\x20 image: ghcr.io/autobrr/autobrr:latest\n\
             \x20\x20\x20 container_name: autobrr\n\
             \x20\x20\x20 restart: unless-stopped\n\
             \x20\x20\x20 networks:\n\
             \x20\x20\x20\x20\x20 - media-network\n\
             \x20\x20\x20 ports:\n\
             \x20\x20\x20\x20\x20 - \"127.0.0.1:7474:7474\"\n\
             \x20\x20\x20 environment:\n\
             \x20\x20\x20\x20\x20 - PUID=${PUID:-1000}\n\
             \x20\x20\x20\x20\x20 - PGID=${PGID:-1000}\n\
             \x20\x20\x20\x20\x20 - TZ=${TZ:-UTC}\n\
             \x20\x20\x20 volumes:\n\
             \x20\x20\x20\x20\x20 - \"${CONFIG_DIR}/autobrr:/config\"\n",
        );
    }
    if extras.sportarr {
        out.push_str(
            "  sportarr:\n\
             \x20\x20\x20 image: sportarr/sportarr:latest\n\
             \x20\x20\x20 container_name: sportarr\n\
             \x20\x20\x20 restart: unless-stopped\n\
             \x20\x20\x20 networks:\n\
             \x20\x20\x20\x20\x20 - media-network\n\
             \x20\x20\x20 ports:\n\
             \x20\x20\x20\x20\x20 - \"127.0.0.1:1867:1867\"\n\
             \x20\x20\x20 environment:\n\
             \x20\x20\x20\x20\x20 - PUID=${PUID:-1000}\n\
             \x20\x20\x20\x20\x20 - PGID=${PGID:-1000}\n\
             \x20\x20\x20\x20\x20 - TZ=${TZ:-UTC}\n\
             \x20\x20\x20 volumes:\n\
             \x20\x20\x20\x20\x20 - \"${CONFIG_DIR}/sportarr:/config\"\n\
             \x20\x20\x20\x20\x20 - \"${DATA_DIR}:/data\"\n",
        );
    }
    out
}

/// Write (or remove) the override file to match the selection.
/// Removing all extras deletes the file — the base fleet is untouched.
pub fn write_override(install_dir: &Path, extras: &Extras) -> Result<()> {
    let path = install_dir.join("docker-compose.override.yml");
    if extras.any() {
        std::fs::write(&path, render_override_yml(extras)).context("writing override file")?;
    } else if path.exists() {
        std::fs::remove_file(&path).context("removing override file")?;
    }
    Ok(())
}

/// Create the data dirs the extras need. Mirrors the installer's layout.
pub fn ensure_data_dirs(install_dir: &Path, extras: &Extras) -> Result<()> {
    let data = install_dir.join("data");
    let mut dirs = Vec::new();
    if extras.lidarr {
        dirs.push("media/music");
        dirs.push("downloads/lidarr");
    }
    if extras.sportarr {
        dirs.push("media/sports");
        dirs.push("downloads/sportarr");
    }
    for d in dirs {
        std::fs::create_dir_all(data.join(d)).context("creating data dir")?;
    }
    Ok(())
}

/// Exact Bazarr connection values for the guided setup.
/// (Bazarr's settings API schema isn't stable enough to automate safely;
// Porthole shows these instead — same honest boundary as Jellyfin.
pub fn bazarr_manual_steps(sonarr_key: &str, radarr_key: &str) -> Vec<String> {
    vec![
        "Open Bazarr at http://localhost:6767.".to_string(),
        format!("Settings → Sonarr: Host `sonarr`, Port `8989`, API key `{sonarr_key}` → Test → Save."),
        format!("Settings → Radarr: Host `radarr`, Port `7878`, API key `{radarr_key}` → Test → Save."),
        "Settings → Languages: pick your subtitle languages and Save.".to_string(),
        "Settings → Providers: enable OpenSubtitles.com (free account) — Subscene is dead, ignore old guides.".to_string(),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn override_only_has_selected_services() {
        let e = Extras {
            lidarr: true,
            bazarr: false,
            sportarr: true,
            autobrr: true,
        };
        let yml = render_override_yml(&e);
        assert!(yml.contains("lidarr:"));
        assert!(yml.contains("sportarr:"));
        assert!(!yml.contains("bazarr:"));
        assert!(yml.contains("127.0.0.1:8686:8686"));
        assert!(yml.contains("127.0.0.1:1867:1867"));
        assert!(yml.contains("media-network"));
        assert!(yml.contains("${CONFIG_DIR}/lidarr:/config"));
    }

    #[test]
    fn bazarr_gets_memory_cap() {
        let e = Extras {
            bazarr: true,
            ..Extras::default()
        };
        assert!(render_override_yml(&e).contains("mem_limit: 768m"));
    }

    #[test]
    fn write_and_remove_override() {
        let dir = std::env::temp_dir().join("porthole-extras-test");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let e = Extras {
            lidarr: true,
            ..Extras::default()
        };
        write_override(&dir, &e).unwrap();
        assert!(dir.join("docker-compose.override.yml").exists());
        write_override(&dir, &Extras::default()).unwrap();
        assert!(!dir.join("docker-compose.override.yml").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn data_dirs_created() {
        let dir = std::env::temp_dir().join("porthole-extras-dirs-test");
        let _ = std::fs::remove_dir_all(&dir);
        let e = Extras {
            lidarr: true,
            sportarr: true,
            ..Extras::default()
        };
        ensure_data_dirs(&dir, &e).unwrap();
        assert!(dir.join("data/media/music").exists());
        assert!(dir.join("data/downloads/lidarr").exists());
        assert!(dir.join("data/media/sports").exists());
        assert!(!dir.join("data/media/movies").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
