//! Phase 9 — your storage, your way.
//!
//! Two paths:
//! - **Cloud (rclone)**: your library lives encrypted on Google Drive /
//!   pCloud / Dropbox; a local cache keeps streaming smooth; finished
//!   downloads are moved up automatically on a schedule.
//! - **Local pool (mergerfs)**: combine drives into one path (guided,
//!   mostly manual — the expert trap Porthole removes is the *wiring*,
//!   not the hardware).
//!
//! The debrid cloud (Decypharr DFS/WebDAV, Phase 5) remains the
//! zero-config option. This module is for *your own* storage.

use std::path::Path;

/// Which cloud backend the user picked.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum CloudBackend {
    #[default]
    GoogleDrive,
    PCloud,
    Dropbox,
}

impl CloudBackend {
    pub fn label(&self) -> &'static str {
        match self {
            CloudBackend::GoogleDrive => "Google Drive",
            CloudBackend::PCloud => "pCloud",
            CloudBackend::Dropbox => "Dropbox",
        }
    }

    pub fn rclone_type(&self) -> &'static str {
        match self {
            CloudBackend::GoogleDrive => "drive",
            CloudBackend::PCloud => "pcloud",
            CloudBackend::Dropbox => "dropbox",
        }
    }

    /// Honest one-liner per backend (from the Oct 2026 research).
    pub fn blurb(&self) -> &'static str {
        match self {
            CloudBackend::GoogleDrive => "Works, but 750 GB/day upload cap and 5 TB max file.",
            CloudBackend::PCloud => "Best media profile; lifetime plans. Secondary backend only.",
            CloudBackend::Dropbox => "~3 TB plan ceiling is too small for big libraries.",
        }
    }
}

/// Generate an rclone.conf with:
/// - `[cloud]` — the user's backend (tokens filled in by `rclone config`)
/// - `[crypt]` — a crypt wrapper (filename + directory encryption ON).
///   The provider sees ciphertext + metadata only.
///
/// The crypt password is generated by Porthole and MUST be backed up —
/// losing it = data permanently unrecoverable.
pub fn render_rclone_conf(backend: &CloudBackend, crypt_password: &str) -> String {
    format!(
        "# Generated by Porthole — DO NOT commit to git.\n\
         # Back up this file (encrypted) in two places. Losing the crypt\n\
         # password means your cloud library is unrecoverable.\n\
         [cloud]\n\
         type = {rtype}\n\
         # Run `rclone config` to authorize {label}, or paste tokens below.\n\
         \n\
         [crypt]\n\
         type = crypt\n\
         remote = cloud:/porthole-media\n\
         password = {pw}\n\
         password2 =\n\
         filename_encryption = standard\n\
         directory_name_encryption = true\n",
        rtype = backend.rclone_type(),
        label = backend.label(),
        pw = crypt_password,
    )
}

/// Systemd service that mounts the crypt remote.
/// Media-tuned VFS presets (from the Oct 2026 research):
/// - `--vfs-cache-mode full` (remux seek/resume breaks without it)
/// - 10–30 GB sparse cache is enough per 4K stream
/// - buffer 32–64M (256M OOMed a box in 2026)
/// - `--allow-other` (needs `user_allow_other` in /etc/fuse.conf)
pub fn render_mount_service(install_dir: &Path, cache_gb: u32) -> String {
    let config = install_dir.join("configs/rclone/rclone.conf");
    let mountpoint = install_dir.join("mnt/cloud");
    let cache_dir = install_dir.join("configs/rclone/cache");
    format!(
        "[Unit]\n\
         Description=Porthole rclone cloud mount\n\
         After=network-online.target\n\
         Wants=network-online.target\n\
         \n\
         [Service]\n\
         Type=notify\n\
         ExecStartPre=/bin/mkdir -p {mount} {cache}\n\
         ExecStart=/usr/bin/rclone mount crypt: {mount} \\\n\
         \x20\x20 --config {conf} \\\n\
         \x20\x20 --vfs-cache-mode full \\\n\
         \x20\x20 --vfs-cache-max-size {cache_g}G \\\n\
         \x20\x20 --buffer-size 64M \\\n\
         \x20\x20 --vfs-read-ahead 128M \\\n\
         \x20\x20 --allow-other \\\n\
         \x20\x20 --dir-cache-time 5m \\\n\
         \x20\x20 --poll-interval 30s\n\
         ExecStop=/bin/fusermount -uz {mount}\n\
         Restart=on-failure\n\
         RestartSec=10\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        mount = mountpoint.display(),
        cache = cache_dir.display(),
        conf = config.display(),
        cache_g = cache_gb,
    )
}

/// The upload mover script: lock-guarded `rclone move`.
/// Poll-driven (systemd timer) beats event-driven on reliability.
/// - `--min-age 15m`: don't move files still being written
/// - `--delete-empty-src-dirs`: keep the local tree tidy
/// - `--drive-stop-on-upload-limit`: pause on 750 GB/day, don't error
/// - `--max-transfer 700G`: stay under the cap
/// - partial-file excludes: never upload half-written downloads
/// - `--bwlimit` timetable: uncapped overnight, capped daytime
pub fn render_mover_script(install_dir: &Path) -> String {
    let config = install_dir.join("configs/rclone/rclone.conf");
    let src = install_dir.join("data/media");
    format!(
        "#!/bin/bash\n\
         # Generated by Porthole — moves finished local media to the cloud.\n\
         set -euo pipefail\n\
         LOCK=\"{inst}/configs/rclone/mover.lock\"\n\
         exec 9>\"$LOCK\"\n\
         flock -n 9 || {{ echo \"mover already running\"; exit 0; }}\n\
         /usr/bin/rclone move \"{src}\" crypt: \\\n\
         \x20\x20 --config \"{conf}\" \\\n\
         \x20\x20 --min-age 15m \\\n\
         \x20\x20 --delete-empty-src-dirs \\\n\
         \x20\x20 --exclude \"*.partial~\" \\\n\
         \x20\x20 --exclude \"*.!qB\" \\\n\
         \x20\x20 --drive-stop-on-upload-limit \\\n\
         \x20\x20 --max-transfer 700G \\\n\
         \x20\x20 --bwlimit \"01:00,off 08:00,30M\" \\\n\
         \x20\x20 -v\n",
        inst = install_dir.display(),
        src = src.display(),
        conf = config.display(),
    )
}

/// Systemd timer: run the mover every 30 minutes.
pub fn render_mover_timer() -> String {
    String::from(
        "[Unit]\n\
         Description=Porthole cloud upload mover\n\
         \n\
         [Timer]\n\
         OnBootSec=5min\n\
         OnUnitActiveSec=30min\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n",
    )
}

/// Check that FUSE allows `--allow-other`.
/// Classic trap: without `user_allow_other` in /etc/fuse.conf,
/// Plex gets permission denied on the mount.
pub fn check_fuse_allow_other() -> Result<(), String> {
    let conf = std::fs::read_to_string("/etc/fuse.conf").unwrap_or_default();
    let ok = conf
        .lines()
        .any(|l| l.trim() == "user_allow_other" && !l.trim_start().starts_with('#'));
    if ok {
        Ok(())
    } else {
        Err("`user_allow_other` is not enabled in /etc/fuse.conf — the mount won't be visible to Plex. Run: echo user_allow_other | sudo tee -a /etc/fuse.conf".to_string())
    }
}

/// The hardlink smoke test — the killer integration detail.
/// *arrs must import LOCALLY, never through an rclone mount (FUSE can't
/// hardlink; atomic moves break across filesystems). Two bind mounts of
/// the same host volume are different vfsmounts — `link()` returns EXDEV
/// and the *arr silently falls back to FULL copies (229 GB duplicates
/// documented). Porthole tests `touch`+`ln` *inside a container*.
pub fn hardlink_smoke_test(install_dir: &Path) -> Result<(), String> {
    // Find a running *arr container to test inside.
    let out = std::process::Command::new("docker")
        .args(["ps", "--format", "{{.Names}}"])
        .output()
        .map_err(|e| format!("docker not available: {e}"))?;
    let names = String::from_utf8_lossy(&out.stdout);
    let container = names
        .lines()
        .find(|n| *n == "sonarr" || *n == "radarr" || *n == "lidarr")
        .ok_or_else(|| "no *arr container running to test inside".to_string())?;
    let data_dir = install_dir.join("data");
    // The test must run against the same /data the containers see.
    let probe =
        "touch /data/.porthole-link-test && ln /data/.porthole-link-test /data/.porthole-link-test2 && rm /data/.porthole-link-test /data/.porthole-link-test2 && echo OK";
    let out = std::process::Command::new("docker")
        .args(["exec", container, "sh", "-c", probe])
        .output()
        .map_err(|e| format!("docker exec failed: {e}"))?;
    let _ = data_dir; // (host path documented for the operator)
    if out.status.success() && String::from_utf8_lossy(&out.stdout).contains("OK") {
        Ok(())
    } else {
        Err(format!(
            "hardlink test FAILED inside {container} — imports would silently become full copies. Check that /data is one bind mount at the same container path everywhere."
        ))
    }
}

/// Plain-language storage explainer for the Help view.
pub fn storage_explainer() -> Vec<String> {
    vec![
        "Where your library lives — three options:".to_string(),
        "".to_string(),
        "Debrid cloud (default): your debrid service holds the files.".to_string(),
        "Porthole mounts it or links it. Zero setup, zero disk.".to_string(),
        "".to_string(),
        "Your own cloud (rclone): Google Drive, pCloud, Dropbox —".to_string(),
        "encrypted before upload, so the provider sees only ciphertext.".to_string(),
        "Finished downloads move up automatically every 30 minutes.".to_string(),
        "".to_string(),
        "Local disks (mergerfs): combine drives into one path. Your".to_string(),
        "hardware, your control — Porthole guides the wiring.".to_string(),
        "".to_string(),
        "The golden rule: the *arrs always import to LOCAL disk first.".to_string(),
        "Hardlinks are instant and free; copying across filesystems is".to_string(),
        "not. Porthole tests this at install — silently duplicated".to_string(),
        "libraries are the classic self-hosting disaster.".to_string(),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rclone_conf_has_crypt() {
        let conf = render_rclone_conf(&CloudBackend::GoogleDrive, "secret123");
        assert!(conf.contains("[crypt]"));
        assert!(conf.contains("type = crypt"));
        assert!(conf.contains("filename_encryption = standard"));
        assert!(conf.contains("directory_name_encryption = true"));
        assert!(conf.contains("type = drive"));
        // Never commit hints.
        assert!(conf.contains("DO NOT commit"));
    }

    #[test]
    fn mount_service_has_vfs_presets() {
        let svc = render_mount_service(Path::new("/install"), 20);
        assert!(svc.contains("--vfs-cache-mode full"));
        assert!(svc.contains("--allow-other"));
        assert!(svc.contains("--vfs-cache-max-size 20G"));
        assert!(svc.contains("--buffer-size 64M"));
    }

    #[test]
    fn mover_has_safety_flags() {
        let script = render_mover_script(Path::new("/install"));
        assert!(script.contains("flock -n"));
        assert!(script.contains("--min-age 15m"));
        assert!(script.contains("--delete-empty-src-dirs"));
        assert!(script.contains("--drive-stop-on-upload-limit"));
        assert!(script.contains("--max-transfer 700G"));
        assert!(script.contains("--bwlimit"));
    }

    #[test]
    fn backend_blurbs_are_honest() {
        assert!(CloudBackend::GoogleDrive.blurb().contains("750 GB/day"));
        assert!(CloudBackend::Dropbox.blurb().contains("3 TB"));
    }
}
